"""Stateful connection manager for the Meshtastic TCP interface.

Hermes tool handlers are stateless functions, but a Meshtastic link is a
long-lived object with a background receive thread. This module owns a single
process-wide connection plus the observer that feeds the knowledge base.

`meshtastic` is a declared (hard) dependency, normally installed automatically by
pip. It is still imported lazily inside `connect()` so a bare directory-drop
install (no pip step) can load — and its KB-query tools can run — even when the
radio stack happens to be missing.
"""

from __future__ import annotations

import logging
import os
import sys
import threading
from typing import Any

logger = logging.getLogger(__name__)

DEFAULT_TCP_PORT = 4403


def enable_debug_logging() -> bool:
    """If MESHTASTIC_DEBUG is truthy, route this plugin's loggers to stderr at DEBUG.

    Self-contained on purpose: the Hermes gateway logs at WARNING unless started with
    ``-v``/``-vv`` (and its systemd unit is regenerated by ``hermes gateway`` commands),
    so this gives a plugin-owned switch whose output reaches ``journalctl`` regardless.
    Idempotent across repeated plugin registration.
    """
    if os.environ.get("MESHTASTIC_DEBUG", "").strip().lower() not in {"1", "true", "yes", "on"}:
        return False

    # Hermes loads plugins under a mangled namespace (e.g.
    # `hermes_plugins.<key>__meshtastic_platform.adapter`), so we can't target our
    # logger names directly. Attach a stderr handler to the ROOT logger that only
    # emits meshtastic records, and lower the root level so DEBUG/INFO propagate to
    # it. The gateway's own handler keeps its WARNING level, so nothing else is noisier.
    # Match THIS plugin's loggers only (real names or Hermes' mangled
    # `hermes_plugins.<key>__meshtastic_platform.adapter` form) — but NOT the noisy
    # `meshtastic.*` radio library logger.
    root = logging.getLogger()
    # If the gateway already has a root handler that emits WARNING+, only take records
    # BELOW WARNING here so WARNING/ERROR aren't logged twice. In standalone use (no
    # such handler) we emit everything.
    _other_warn = any(
        h.level <= logging.WARNING for h in root.handlers if not getattr(h, "_mesh_debug", False)
    )

    class _PluginOnly(logging.Filter):
        def filter(self, record: logging.LogRecord) -> bool:
            n = record.name
            if "meshtastic_platform" not in n and "meshtastic_hermes" not in n:
                return False
            if _other_warn and record.levelno >= logging.WARNING:
                return False  # let the existing root handler emit it (no duplicate)
            return True

    if not any(getattr(h, "_mesh_debug", False) for h in root.handlers):
        handler = logging.StreamHandler(sys.stderr)
        handler.setLevel(logging.DEBUG)
        handler.setFormatter(logging.Formatter("%(levelname)s %(name)s: %(message)s"))
        handler.addFilter(_PluginOnly())
        handler._mesh_debug = True  # type: ignore[attr-defined]  # marker for dedup
        root.addHandler(handler)
    if root.level > logging.DEBUG or root.level == logging.NOTSET:
        root.setLevel(logging.DEBUG)
    # Lowering root to DEBUG would otherwise unleash the radio library's very verbose
    # per-packet DEBUG; keep it at WARNING so only our plugin's logs show.
    logging.getLogger("meshtastic").setLevel(logging.WARNING)
    return True


class MeshtasticUnavailable(RuntimeError):
    """Raised when the optional `meshtastic` package is not importable."""


def _import_meshtastic():
    try:
        import meshtastic  # noqa: F401
        import meshtastic.tcp_interface  # noqa: F401

        return meshtastic
    except ImportError as exc:  # pragma: no cover - exercised only without extra
        raise MeshtasticUnavailable(
            "The 'meshtastic' package is not installed in Hermes' Python environment. "
            "Install it with: pip install meshtastic  "
            "(normally pulled in automatically by pip install meshtastic-hermes-plugin)."
        ) from exc


class ConnectionManager:
    """Owns the active TCPInterface and wires the receive observer."""

    def __init__(self) -> None:
        self._iface: Any = None
        self._host: str | None = None
        self._port: int = DEFAULT_TCP_PORT
        self._lock = threading.Lock()
        self._observer = None  # set lazily to avoid import cycle
        # Supervisor: keep the link up while connection is desired, so the gateway
        # keeps RECEIVING across drops without anyone re-calling connect().
        self._want_connected = False
        self._stop = threading.Event()
        self._supervisor: threading.Thread | None = None

    # ------------------------------------------------------------------

    def connect(self, host: str, port: int = DEFAULT_TCP_PORT) -> dict[str, Any]:
        """Open a TCP connection to `host` and subscribe the observer.

        Idempotent-ish: an existing connection is closed first.
        """
        self._host = host
        self._port = port
        self._want_connected = True
        self._stop.clear()
        try:
            self._open()
        except MeshtasticUnavailable:
            raise  # radio lib genuinely missing — no point supervising
        except Exception as exc:
            # Node unreachable at startup: don't fail hard, let the supervisor retry
            # (keeps "connected if MESHTASTIC_HOST is set" true once it comes up).
            logger.warning("Initial Meshtastic connect to %s failed: %s (supervisor will retry)", host, exc)
        self._ensure_supervisor()
        return self.status()

    def _open(self) -> None:
        """(Re)open the interface and wire subscriptions. Raises on failure."""
        mesh = _import_meshtastic()
        from pubsub import pub

        from . import observer as _observer

        with self._lock:
            # Always clean up first — even after a loss left _iface=None, stale pubsub
            # subscriptions may linger and must be dropped before re-subscribing.
            self._close_locked()

            iface = mesh.tcp_interface.TCPInterface(self._host, portNumber=self._port)
            self._iface = iface

            # Subscribe to the parent topic to capture ALL packet types, including
            # encrypted PRIVATE_APP traffic on channels we cannot read. (pubsub topics
            # are global, so the observer keeps receiving across reconnects.)
            self._observer = _observer.get_observer()
            pub.subscribe(self._observer.on_receive, "meshtastic.receive")
            pub.subscribe(self._on_connection_lost, "meshtastic.connection.lost")

    def _ensure_supervisor(self) -> None:
        if self._supervisor and self._supervisor.is_alive():
            return
        self._supervisor = threading.Thread(
            target=self._supervise, name="meshtastic-reconnect", daemon=True
        )
        self._supervisor.start()

    def _supervise(self) -> None:
        """Keep the link up while connection is desired (reconnect with backoff)."""
        backoff = 2
        while self._want_connected and not self._stop.is_set():
            if self._iface is None:
                try:
                    self._open()
                    logger.info("Meshtastic reconnected to %s", self._host)
                    backoff = 2
                except Exception as exc:
                    logger.warning("Meshtastic reconnect failed: %s (retry in %ss)", exc, backoff)
                    self._stop.wait(backoff)
                    backoff = min(backoff * 2, 60)
                    continue
            self._stop.wait(3)  # poll for drops

    def _on_connection_lost(self, interface=None) -> None:
        with self._lock:
            self._iface = None
        logger.warning("Meshtastic connection lost — supervisor will reconnect")

    def disconnect(self) -> dict[str, Any]:
        # Stop the supervisor first so it doesn't immediately reconnect.
        self._want_connected = False
        self._stop.set()
        with self._lock:
            self._close_locked()
        return {"connected": False}

    def _close_locked(self) -> None:
        try:
            from pubsub import pub

            if self._observer is not None:
                pub.unsubscribe(self._observer.on_receive, "meshtastic.receive")
            # Always drop the loss subscription too, so reconnects don't accumulate
            # duplicate handlers (which made "connection lost" fire N times).
            pub.unsubscribe(self._on_connection_lost, "meshtastic.connection.lost")
        except Exception:
            pass
        if self._iface is not None:
            try:
                self._iface.close()
            except Exception:
                pass
        self._iface = None
        self._host = None

    # ------------------------------------------------------------------

    def is_connected(self) -> bool:
        return self._iface is not None

    @property
    def iface(self) -> Any:
        if self._iface is None:
            raise RuntimeError("Not connected. Call meshtastic_connect first.")
        return self._iface

    def my_node_id(self) -> str | None:
        if self._iface is None:
            return None
        info = getattr(self._iface, "myInfo", None)
        if info is None:
            return None
        return f"!{info.my_node_num:08x}"

    def status(self) -> dict[str, Any]:
        return {
            "connected": self.is_connected(),
            "host": self._host,
            "node_id": self.my_node_id(),
        }


# Process-wide singletons live in a fixed sys.modules slot (NOT module globals).
# Hermes loads the tools plugin under a mangled package name while the platform
# adapter imports `meshtastic_hermes` as a top-level package (via its sys.path shim),
# so there are TWO copies of this module — each with its own globals. Keying the
# singletons off a fixed sys.modules entry makes both copies share ONE
# ConnectionManager + Observer + KB, i.e. a single radio connection instead of two
# competing ones.
_SHARED_KEY = "meshtastic_hermes._shared_state"


def _shared_state():
    import types

    st = sys.modules.get(_SHARED_KEY)
    if st is None:
        st = types.ModuleType(_SHARED_KEY)
        st.manager = None
        st.observer = None
        sys.modules[_SHARED_KEY] = st
    return st


def get_manager() -> ConnectionManager:
    st = _shared_state()
    if st.manager is None:
        st.manager = ConnectionManager()
    return st.manager
