"""Stateful connection manager for the Meshtastic TCP interface.

Hermes tool handlers are stateless functions, but a Meshtastic link is a
long-lived object with a background receive thread. This module owns a single
process-wide connection plus the observer that feeds the knowledge base.

`meshtastic` is a declared (hard) dependency, normally installed automatically by
pip. It is still imported lazily inside `connect()` so a bare directory-drop
install (no pip step) can load — and its KB-query tools can run — even when the
radio stack happens to be missing.
"""

from __future__ import annotations

import logging
import os
import sys
import threading
from typing import Any

logger = logging.getLogger(__name__)

DEFAULT_TCP_PORT = 4403


def enable_debug_logging() -> bool:
    """If MESHTASTIC_DEBUG is truthy, route this plugin's loggers to stderr at DEBUG.

    Self-contained on purpose: the Hermes gateway logs at WARNING unless started with
    ``-v``/``-vv`` (and its systemd unit is regenerated by ``hermes gateway`` commands),
    so this gives a plugin-owned switch whose output reaches ``journalctl`` regardless.
    Idempotent across repeated plugin registration.
    """
    if os.environ.get("MESHTASTIC_DEBUG", "").strip().lower() not in {"1", "true", "yes", "on"}:
        return False

    # Hermes loads plugins under a mangled namespace (e.g.
    # `hermes_plugins.<key>__meshtastic_platform.adapter`), so we can't target our
    # logger names directly. Attach a stderr handler to the ROOT logger that only
    # emits meshtastic records, and lower the root level so DEBUG/INFO propagate to
    # it. The gateway's own handler keeps its WARNING level, so nothing else is noisier.
    # Match THIS plugin's loggers only (real names or Hermes' mangled
    # `hermes_plugins.<key>__meshtastic_platform.adapter` form) — but NOT the noisy
    # `meshtastic.*` radio library logger.
    class _PluginOnly(logging.Filter):
        def filter(self, record: logging.LogRecord) -> bool:
            n = record.name
            return "meshtastic_platform" in n or "meshtastic_hermes" in n

    root = logging.getLogger()
    if not any(getattr(h, "_mesh_debug", False) for h in root.handlers):
        handler = logging.StreamHandler(sys.stderr)
        handler.setLevel(logging.DEBUG)
        handler.setFormatter(logging.Formatter("%(levelname)s %(name)s: %(message)s"))
        handler.addFilter(_PluginOnly())
        handler._mesh_debug = True  # type: ignore[attr-defined]  # marker for dedup
        root.addHandler(handler)
    if root.level > logging.DEBUG or root.level == logging.NOTSET:
        root.setLevel(logging.DEBUG)
    # Lowering root to DEBUG would otherwise unleash the radio library's very verbose
    # per-packet DEBUG; keep it at WARNING so only our plugin's logs show.
    logging.getLogger("meshtastic").setLevel(logging.WARNING)
    return True


class MeshtasticUnavailable(RuntimeError):
    """Raised when the optional `meshtastic` package is not importable."""


def _import_meshtastic():
    try:
        import meshtastic  # noqa: F401
        import meshtastic.tcp_interface  # noqa: F401

        return meshtastic
    except ImportError as exc:  # pragma: no cover - exercised only without extra
        raise MeshtasticUnavailable(
            "The 'meshtastic' package is not installed in Hermes' Python environment. "
            "Install it with: pip install meshtastic  "
            "(normally pulled in automatically by pip install meshtastic-hermes-plugin)."
        ) from exc


class ConnectionManager:
    """Owns the active TCPInterface and wires the receive observer."""

    def __init__(self) -> None:
        self._iface: Any = None
        self._host: str | None = None
        self._lock = threading.Lock()
        self._observer = None  # set lazily to avoid import cycle

    # ------------------------------------------------------------------

    def connect(self, host: str, port: int = DEFAULT_TCP_PORT) -> dict[str, Any]:
        """Open a TCP connection to `host` and subscribe the observer.

        Idempotent-ish: an existing connection is closed first.
        """
        mesh = _import_meshtastic()
        from pubsub import pub

        from . import observer as _observer

        with self._lock:
            if self._iface is not None:
                self._close_locked()

            iface = mesh.tcp_interface.TCPInterface(host, portNumber=port)
            self._iface = iface
            self._host = host

            # Subscribe to the parent topic to capture ALL packet types,
            # including encrypted PRIVATE_APP traffic on channels we cannot read.
            self._observer = _observer.get_observer()
            pub.subscribe(self._observer.on_receive, "meshtastic.receive")
            # Detect drops (e.g. the node resetting the link / "Connection reset by
            # peer") so is_connected() stays truthful and the next use cleanly
            # reconnects instead of timing out on a dead interface.
            pub.subscribe(self._on_connection_lost, "meshtastic.connection.lost")

        return self.status()

    def _on_connection_lost(self, interface=None) -> None:
        with self._lock:
            self._iface = None
        logger.warning("Meshtastic connection lost — marked disconnected (reconnect on next use)")

    def disconnect(self) -> dict[str, Any]:
        with self._lock:
            self._close_locked()
        return {"connected": False}

    def _close_locked(self) -> None:
        if self._observer is not None:
            try:
                from pubsub import pub

                pub.unsubscribe(self._observer.on_receive, "meshtastic.receive")
            except Exception:
                pass
        if self._iface is not None:
            try:
                self._iface.close()
            except Exception:
                pass
        self._iface = None
        self._host = None

    # ------------------------------------------------------------------

    def is_connected(self) -> bool:
        return self._iface is not None

    @property
    def iface(self) -> Any:
        if self._iface is None:
            raise RuntimeError("Not connected. Call meshtastic_connect first.")
        return self._iface

    def my_node_id(self) -> str | None:
        if self._iface is None:
            return None
        info = getattr(self._iface, "myInfo", None)
        if info is None:
            return None
        return f"!{info.my_node_num:08x}"

    def status(self) -> dict[str, Any]:
        return {
            "connected": self.is_connected(),
            "host": self._host,
            "node_id": self.my_node_id(),
        }


# Process-wide singletons live in a fixed sys.modules slot (NOT module globals).
# Hermes loads the tools plugin under a mangled package name while the platform
# adapter imports `meshtastic_hermes` as a top-level package (via its sys.path shim),
# so there are TWO copies of this module — each with its own globals. Keying the
# singletons off a fixed sys.modules entry makes both copies share ONE
# ConnectionManager + Observer + KB, i.e. a single radio connection instead of two
# competing ones.
_SHARED_KEY = "meshtastic_hermes._shared_state"


def _shared_state():
    import types

    st = sys.modules.get(_SHARED_KEY)
    if st is None:
        st = types.ModuleType(_SHARED_KEY)
        st.manager = None
        st.observer = None
        sys.modules[_SHARED_KEY] = st
    return st


def get_manager() -> ConnectionManager:
    st = _shared_state()
    if st.manager is None:
        st.manager = ConnectionManager()
    return st.manager
